### ISSUE TITLE
Failed to Program PDI after HW Compilation, Suspected AMI/AVED/Vivado Version Compatibility Issue

### ISSUE THREAD

**Issue by lockezhan** [Xilinx/SLASH#30]
## Problem Description
- Following the dev branch workflow, I successfully compiled the SLASH project in HW mode, and generated the corresponding `vrtbin` and `pdi` files.
- However, programming the `pdi` file always fails, whether using `vrt::Device device(bdf, vrtbinFile)` or `ami_tool cfgmem_program -d <bdf> -t <type> -i <path> -p <n>`.
- Initially, I suspected the `--segment` parameter, but removing it did not resolve the issue.
- My current ami_tool version is 2.3.0, and all related dependencies and drivers are aligned to this version.

## Environment Information
- OS: Ubuntu 22.04, Kernel 5.15
- Accelerator Card: Alveo V80 PQ
- ami_tool version: 2.3.0 (Hash: 0bab29e568f64a25f17425c0ffd1c0e89609b6d1, Build date: 2024-03-07)
- Driver version: 2.3.0
- Due to environment constraints, compilation and programming are done on separate machines:  
  - The machine with Alveo V80 installed for programming uses Vitis/Vivado 2024.1  
  - The machine used for compiling the SLASH project uses Vitis/Vivado 2024.2
- According to the AVED official documentation, only Vivado 2024.1 is currently supported ([AVED Documentation](https://xilinx.github.io/AVED/)).

## Actual Command Used
```
sudo ami_tool cfgmem_program -d a1:00.0 -t primary -i /home/bjut316-v80/SLASH/examples/01_aximm/design.pdi -p 0
```

## Terminal Output and Error Log
```
----------------------------------------------
Device | a1:00.0
----------------------------------------------
Current Configuration
----------------------------------------------
UUID   | 3907c6f088e5c23471ab99aae09a9928
----------------------------------------------
Incoming Configuration
----------------------------------------------
UUID      | bf0dbb51390393e5f07638c001d5482e
Path      | /home/bjut316-v80/SLASH/examples/01_aximm/design.pdi
Partition | 0
----------------------------------------------
Are you sure you wish to proceed? [Y/n]: Y

Updating base flash image...
[####################################################################################################] 100% | 
Image programming complete.
Will do a hot reset to boot into partition 0. This may take a minute...
Error: could not select boot partition
ENODEV: No such device [ami_dev_find_next:479].
```
> Note: Running `./01_aximm a1:00.0 01_aximm_hw.vrtbin` results in the program hanging, so no output can be captured.

## Main Questions and Requests
- Is the programming failure related to compatibility issues between ami_tool, AVED, and Vitis/Vivado versions?
- If it is a version compatibility issue, does AVED plan to support Vivado 2024.2 in the near future? Are there any recommendations for adaptation?
- If it is not a compatibility issue, please help analyze other potential causes for the `could not select boot partition` and `ENODEV` errors and provide troubleshooting suggestions.
- In theory, programming should succeed when all official deployment requirements are met on the same device. If there are additional considerations, please point them out.

## Reference
- https://xilinx.github.io/AVED/

Thank you!

**Comment by hpc-aulmamei** [comment]
Hi @lockezhan. Please take a look at the deployment readme. Right now, a special image needs to be placed in partition 1 of the OSPI in order for SLASH to work. The deploy/base_pdi folder contains the necessary scripts to make that work. Once you build the base design, it needs to be programmed using the ami_tool. We are currently using a version of AVED with some changes, to support partial programming.

**Comment by lockezhan** [comment]
Hi@hpc-aulmamei. Thank you for your reply. I now understand that due to a previous compilation error, I did not flash partition 1 of the OSPI, which was my oversight. Additionally, I would like to confirm whether the AVED version with partial programming support that you are using is implemented within the SLASH project itself, or if it is a new version obtained from another source? If it is from another source, could you please provide information on how to obtain it, or share a relevant link? Thank you very much!

**Comment by lockezhan** [comment]
Hi @hpc-aulmamei .Thank you for your reply. I now understand that due to a previous compilation error, I did not flash partition 1 of the OSPI, which was my oversight.

Additionally, I noticed in the deployment readme that there is a step to apply an AVED patch to the repository:
```
cd <project_root>/submodules/v80-vitis-flow/submodules/aved/
git apply ../../../../deploy/aved.patch
```
I would like to confirm if this patch is the modification you mentioned for supporting partial programming. If I apply this patch as instructed, will I get the same AVED functionality as you are currently using? Thank you very much!

**Comment by lockezhan** [comment]
Hi @hpc-aulmamei .Thank you for your reply. I now understand that due to a previous compilation error, I did not flash partition 1 of the OSPI, which was my oversight.

**Comment by lockezhan** [comment]
Hi @hpc-aulmamei .

I have burned `base.pdi` into partition 1 and updated the AMI driver. The compilation and installation of the VRT software stack were successful. However, during runtime, I encountered the following issues.

# Problem Description

While running the device `ALVEO V80 PQ`, the following errors occurred:
- FPGA device initialization failed with the following logs:
  ```
  ami 0000:a1:00.0: ERROR : Invalid table size
  ami 0000:a1:00.0: ERROR : Failed to read Vendor Specific Region (VSEC)
  ami: probe of 0000:a1:00.0 failed with error -22
  ```
- The filesystem switched to read-only mode, which might affect the driver’s ability to read/write.
- Networking services failed, and D-Bus-related issues might be impacting device functionality.

The device indicator lights show that the hardware is functioning, but the device cannot be connected without performing a physical power cycle.

# Device Information

```
  v80-smi list
  --------------------------------------------------------------------
  Listing V80 devices 
  --------------------------------------------------------------------
  V80 device found with BDF: 0000:a1:00.0
```

# Error Logs

Below are the complete error logs:
```
Jul 05 20:50:50 bjut316v80-X640-G40 kernel: ami 0000:a1:00.0: ERROR : Invalid table size
Jul 05 20:50:50 bjut316v80-X640-G40 kernel: ami 0000:a1:00.0: ERROR : Failed to read Vendor Specific Region (VSEC)
Jul 05 20:50:50 bjut316v80-X640-G40 kernel: ami: probe of 0000:a1:00.0 failed with error -22
Jul 05 20:50:51 bjut316v80-X640-G40 kernel: ami: probe of 0000:a1:00.1 failed with error -22
Jul 05 22:15:02 bjut316v80-X640-G40 kernel: EXT4-fs (sda2): re-mounted. Opts: errors=remount-ro. Quota mode: none.
Jul 05 22:15:05 bjut316v80-X640-G40 networkd-dispatcher[2094]: ERROR: Unknown state for interface NetworkctlListState...
Jul 05 22:15:14 bjut316v80-X640-G40 pipewire[3180]: mod.rt: RTKit error: org.freedesktop.DBus.Error.AccessDenied
Jul 05 22:21:32 bjut316v80-X640-G40 pulseaudio[4350]: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply
```

# Assistance Required

- What could be the possible causes of these errors?
- Do I need to update the driver or firmware?
- Are there any further debugging suggestions?

Thank you for your assistance!

**Comment by hpc-aulmamei** [comment]
Hi @lockezhan! Can you explain which example did you build and try to use that got you to these issues? 
DBus and NetworkctlListState errors are likely not related to the V80.

**Comment by lockezhan** [comment]
Hi @hpc-aulmamei . I encountered this problem while building and running the 00_axilite example.
I don't need to modify the host files in the example, right?

**Comment by hpc-aulmamei** [comment]
No, no changes are needed. We will investigate this matter and come back to you with a solution. This is a bug that we encountered while developing SLASH, but it was fixed (or thought so) in a previous push. I'll get back to you soon.

**Comment by lockezhan** [comment]
Thank you very much for your prompt response and for investigating this issue.
I will also double-check my steps to see if there’s anything I might have missed or done incorrectly during the process.

Looking forward to your update!

**Comment by lockezhan** [comment]
# Issue Description

I also compiled the `01_aximm` example and executed the following command at approximately 19:15:
```bash
./01_example a1:00.0 01_example_hw.vrtbin
```
After execution, the system still encountered several issues. Ultimately, a physical reboot was required to restore functionality.

---

1. **Device Health Status Critical**
   ```
   Jul 06 19:15:09 kernel: ami 0000:a1:00.0: AMC OUTPUT : [BIM] AMC health status: CRITICAL
   ```
   - The device reported its health status as "CRITICAL" 

2. **Device Removal**
   ```
   Jul 06 19:15:09 kernel: Removing PCIe device: 0000:a1:00.0
   Jul 06 19:15:10 kernel: ami 0000:a1:00.0: INFO : Successfully removed PCIe device
   ```
   - The system forcibly removed the device

3. **PCIe Link Loss**
   ```
   Jul 06 19:15:10 kernel: igb 0000:a0:00.1 enp160s0f1: PCIe link lost
   Jul 06 19:15:12 kernel: igb 0000:a0:00.0 enp160s0f0: PCIe link lost
   ```
   - PCIe link loss occurred, rendering the device unable to communicate with the host.

4. **Driver Initialization Failure**
   ```
   Jul 06 19:15:20 kernel: ami 0000:a1:00.0: ERROR : Invalid table size
   Jul 06 19:15:20 kernel: ami 0000:a1:00.0: ERROR : Failed to read Vendor Specific Region (VSEC)
   Jul 06 19:15:21 kernel: qdma_is_config_bar: Invalid config bar, err:-4
   ```
   - The driver failed to initialize the device, reporting errors such as "Invalid table size" and "Invalid config bar."

5. **System Resource Allocation Failure**
   ```
   Jul 06 19:15:15 kernel: pcieport 0000:64:02.0: BAR 13: failed to assign [io size 0x1000]
   Jul 06 19:15:15 kernel: pcieport 0000:98:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring
   ```
   - The system was unable to allocate sufficient resources (e.g., I/O space) for the device, causing configuration failures.

6. **Network Device Failure**
   ```
   Jul 06 19:15:27 kernel: NETDEV WATCHDOG: enp160s0f0 (igb): transmit queue 0 timed out
   Jul 06 19:15:27 kernel: WARNING: CPU: 8 PID: 0 at net/sched/sch_generic.c:477 dev_watchdog+0x277/0x280
   ```
   - The network device's transmit queue timed out, potentially related to the PCIe link issues.

**Comment by hpc-aulmamei** [comment]
Hi @lockezhan. Can you try building everything (base pdi + example) from the current dev branch? I added a change to the NoC solution generation and from my internal tests it seems to work. If you can confirm this, it would be greatly appreciated.

**Comment by lockezhan** [comment]
Hi, @hpc-aulmamei .
I'll rebuild everything from scratch, without changing anything else, just including your modification to the NoC solution generation. I’ll get back to you shortly with the results.

Thanks!

**Comment by lockezhan** [comment]
Hi @hpc-aulmamei 
Thank you for all the support and discussion on this issue!

I wanted to provide an update: After further investigation, I discovered that my previous testing failures were actually due to a PCIe device issue on my end, rather than the version compatibility concerns I initially suspected.

Resolution: The issue was resolved after I performed manual flashing of the device. The testing now passes normally and everything works as expected. 

Thank you for your contributions to the V80 board ecosystem!
